/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#d0bcff",
        "on-tertiary": "#3c0091",
        "surface": "#0b1326",
        "inverse-surface": "#dae2fd",
        "on-surface-variant": "#bcc9cd",
        "on-secondary-fixed": "#001a42",
        "on-primary": "#003640",
        "outline-variant": "#3d494c",
        "surface-container-lowest": "#060e20",
        "on-tertiary-fixed": "#23005c",
        "inverse-on-surface": "#283044",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "on-primary-container": "#00424f",
        "on-secondary": "#002e6a",
        "background": "#0b1326",
        "on-surface": "#dae2fd",
        "outline": "#869397",
        "surface-tint": "#4cd7f6",
        "on-error-container": "#ffdad6",
        "secondary-container": "#0566d9",
        "surface-variant": "#2d3449",
        "surface-dim": "#0b1326",
        "secondary": "#adc6ff",
        "surface-bright": "#31394d",
        "on-primary-fixed": "#001f26",
        "on-tertiary-container": "#4900ae",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-high": "#222a3d",
        "on-primary-fixed-variant": "#004e5c",
        "primary-fixed-dim": "#4cd7f6",
        "tertiary-container": "#b395ff",
        "on-secondary-container": "#e6ecff",
        "on-background": "#dae2fd",
        "primary-container": "#06b6d4",
        "tertiary-fixed": "#e9ddff",
        "tertiary": "#d0bcff",
        "surface-container-highest": "#2d3449",
        "on-error": "#690005",
        "primary-fixed": "#acedff",
        "primary": "#4cd7f6",
        "on-tertiary-fixed-variant": "#5516be",
        "secondary-fixed": "#d8e2ff",
        "error": "#ffb4ab",
        "inverse-primary": "#00687a",
        "secondary-fixed-dim": "#adc6ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "md": "16px",
        "gutter": "24px",
        "sm": "8px",
        "container-max": "1280px",
        "base": "4px",
        "lg": "24px",
        "xs": "4px",
        "xl": "40px",
        "margin-desktop": "48px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "HangamePoker", "sans-serif"],
        "body-sm": ["Inter", "HangamePoker", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "HangamePoker", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "HangamePoker", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "HangamePoker", "sans-serif"],
        "label-sm": ["JetBrains Mono", "Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "Inter", "sans-serif"],
        "body-md": ["Inter", "HangamePoker", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "HangamePoker", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "800"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}]
      }
    }
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
